language: crystal

services:
  - docker
  - redis-server

env:
  global:
    - TRAVIS_CI_BUILD=true
  matrix:
    - REDIS_VERSION=redis4

# TODO check against a greater range of Redis versions

script:
  - docker-compose -f docker/$REDIS_VERSION/docker-compose.yml up -d
  - crystal spec